title: "Nikola Veselinov"
description: "Personal site of Nikola Veselinov"
theme: minima
permalink: pretty
markdown: kramdown

minima:
  skin: auto
  navigation:
    - title: "Teaching"
      url: /teaching/
    - title: "Research"
      url: /research/
    - title: "Projects"
      url: /projects/
    - title: "Blog"
      url: /blog/
