title: ""
description: "© 2025 Nikola Veselinov. All rights reserved."
theme: minima
permalink: pretty
markdown: kramdown

minima:
  skin: auto
  show_title: false
  show_footer_links: false

  navigation:
    - title: "Teaching"
      url: /teaching/
    - title: "Research"
      url: /research/
    - title: "Projects"
      url: /projects/
    - title: "Blog"
      url: /blog/

sass:
  style: compressed

include:
  - assets
