title: Nikola Veselinov
description: A minimal site to share my work and thoughts.
theme: minima
markdown: kramdown
permalink: pretty

# Navigation links for the top menu
nav:
  - title: "About"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Research"
    url: "/research"
  - title: "Teaching"
    url: "/teaching"
  - title: "Writing"
    url: "/writing"
  - title: "Blog"
    url: "/blog"
